- hosts: localhost
  tasks:
  - name: Install Git
    become: yes
    become_method: sudo
    yum: name=git state=latest
  - name: Install docker
    become: yes
    become_method: sudo
    yum: name=docker state=latest
  - name: Clone Pet-Clinic
    git: repo=https://github.com/zvikagol/spring-petclinic.git dest=~/Projects/petclinic
  - name: Clone Xura-Training
    git: repo=https://github.com/zvikagol/Xura-training.git dest=~/Projects/Xura update=no
