- hosts: localhost
  tasks:
    - name: get my war
      get_url: url=http://52.58.10.89:8081/artifactory/libs-snapshot-local/org/springframework/samples/spring-petclinic-somethingelse/1.0.0-SNAPSHOT/spring-petclinic-somethingelse-1.0.0-20160214.123214-1.war dest=~/xura/Dockers3/petclinic.war
    - name: build the docker
      docker_image: path="." name=whatever state=build

